# Binary Search

## Questions

### Fully sorted array

1. [704. Binary Search](https://leetcode.com/problems/binary-search)
2. [278. First Bad Version](https://leetcode.com/problems/first-bad-version/description/)
3. [2187. Minimum Time to Complete Trips](https://leetcode.com/problems/minimum-time-to-complete-trips/description/)
4. [69. Sqrt(x)](https://leetcode.com/problems/sqrtx/description/)
5. [35. Search Insert Position](https://leetcode.com/problems/search-insert-position/description/)
6. [1482. Minimum Number of Days to Make m Bouquets](https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/description/)
7. [668. Kth Smallest Number in Multiplication Table](https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/description/)
8.  [719. Find K-th Smallest Pair Distance](https://leetcode.com/problems/find-k-th-smallest-pair-distance/description/)
9.  [1201. Ugly Number III](https://leetcode.com/problems/ugly-number-iii/description/)
11. [34. Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/)
12. [74. Search a 2D Matrix](https://leetcode.com/problems/search-a-2d-matrix/description/)
13. [2089. Find Target Indices After Sorting Array](https://leetcode.com/problems/find-target-indices-after-sorting-array/description/)


### Nearly sorted array


1. [33. Search in Rotated Sorted Array](https://leetcode.com/problems/search-in-rotated-sorted-array/description/)
2. [81. Search in Rotated Sorted Array II](https://leetcode.com/problems/search-in-rotated-sorted-array-ii/description/)
3. [153. Find Minimum in Rotated Sorted Array](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/)
4. [154. Find Minimum in Rotated Sorted Array II](https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/description/)
5. [852. Peak Index in a Mountain Array](https://leetcode.com/problems/peak-index-in-a-mountain-array/description/)
6. [162. Find Peak Element](https://leetcode.com/problems/find-peak-element/description/)
7. [1095. Find in Mountain Array](https://leetcode.com/problems/find-in-mountain-array/description/)


### Min-max

1. [410. Split Array Largest Sum](https://leetcode.com/problems/split-array-largest-sum/description/)
2. [875. Koko Eating Bananas](https://leetcode.com/problems/koko-eating-bananas/description/)
3. [1011. Capacity To Ship Packages Within D Days](https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/description/)
4. [1283. Find the Smallest Divisor Given a Threshold](https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/description/)

### Others

1. [981. Time Based Key-Value Store](https://leetcode.com/problems/time-based-key-value-store/description/)
2. [4. Median of Two Sorted Arrays](https://leetcode.com/problems/median-of-two-sorted-arrays/description/)
3. [374. Guess Number Higher or Lower](https://leetcode.com/problems/guess-number-higher-or-lower/description/)
4. [441. Arranging Coins](https://leetcode.com/problems/arranging-coins/description/)
5. [2300. Successful Pairs of Spells and Potions](https://leetcode.com/problems/successful-pairs-of-spells-and-potions/description/)
6. [540. Single Element in a Sorted Array](https://leetcode.com/problems/single-element-in-a-sorted-array/description/)
7. [367. Valid Perfect Square](https://leetcode.com/problems/valid-perfect-square/description/)
8. [977. Squares of a Sorted Array](https://leetcode.com/problems/squares-of-a-sorted-array/description/)
9. [2616. Minimize the Maximum Difference of Pairs](https://leetcode.com/problems/minimize-the-maximum-difference-of-pairs/description/)
10. [1268. Search Suggestions System](https://leetcode.com/problems/search-suggestions-system/description/)
11. [116. Populating Next Right Pointers in Each Node](https://leetcode.com/problems/populating-next-right-pointers-in-each-node/description/)
12. [1898. Maximum Number of Removable Characters](https://leetcode.com/problems/maximum-number-of-removable-characters/description/)

## Reference

- [https://leetcode.com/discuss/general-discussion/786126/python-powerful-ultimate-binary-search-template-solved-many-problems](https://leetcode.com/discuss/general-discussion/786126/python-powerful-ultimate-binary-search-template-solved-many-problems)
- [Binary Search 101 The-Ultimate-Binary-Search-Handbook](https://leetcode.com/problems/binary-search/solutions/423162/Binary-Search-101-The-Ultimate-Binary-Search-Handbook/)


